"use client"

import { useEffect, useState } from "react"
import { use } from "react"
import { jsPDF } from "jspdf"
import autoTable from "jspdf-autotable"
import { useCallback } from "react"
import { useRouter } from "next/navigation"
import { motion } from "framer-motion"
import type { Expense } from "@/lib/types"
import { formatCurrency, getCurrencySymbol } from "@/lib/utils"
import { Download, Printer, ArrowLeft, Receipt, Calendar, User, Hash, FileText } from "lucide-react"

interface UserProfile {
  name: string
  email: string
  profileImage?: string
}

export default function ReceiptPage(props: { params: Promise<{ id: string }> }) {
  const params = use(props.params)
  const [expense, setExpense] = useState<Expense | null>(null)
  const [userProfile, setUserProfile] = useState<UserProfile | null>(null)
  const [isLoading, setIsLoading] = useState(true)
  const router = useRouter()

  useEffect(() => {
    const fetchData = async () => {
      try {
        const [expenseResponse, profileResponse] = await Promise.all([
          fetch(`/api/expenses/${params.id}`),
          fetch("/api/auth/me")
        ])

        if (expenseResponse.ok && profileResponse.ok) {
          const expenseData = await expenseResponse.json()
          const profileData = await profileResponse.json()
          setExpense(expenseData)
          setUserProfile(profileData)
        } else if (expenseResponse.status === 401) {
          router.push("/auth/login")
        }
      } catch (error) {
        console.error("Failed to fetch data:", error)
      } finally {
        setIsLoading(false)
      }
    }

    fetchData()
  }, [params.id, router])

  const formatCurrencyForPDF = (amount: number, currency: string = "PKR"): string => {
    const actualAmount = amount / 100
    const isWholeNumber = actualAmount % 1 === 0
    
    const formattedAmount = actualAmount.toLocaleString('en-US', {
      minimumFractionDigits: isWholeNumber ? 0 : 2,
      maximumFractionDigits: isWholeNumber ? 0 : 2,
      useGrouping: false
    })

    const currencySymbols: { [key: string]: string } = {
      'PKR': 'Rs',
      'USD': '$',
      'EUR': '€',
      'GBP': '£',
      'AED': 'AED',
      'SAR': 'SAR',
      'INR': '₹',
      'CAD': 'C$',
      'AUD': 'A$'
    }

    const symbol = currencySymbols[currency] || currency
    return `${symbol} ${formattedAmount}`
  }

  const handleExportPDF = useCallback(async () => {
    if (!expense || !userProfile) return

    try {
      const doc = new jsPDF()
      const pageWidth = doc.internal.pageSize.getWidth()

      doc.setFillColor(6, 182, 212)
      doc.rect(0, 0, pageWidth, 60, 'F')
      
      doc.setTextColor(255, 255, 255)
      doc.setFontSize(20)
      doc.setFont("helvetica", "bold")
      doc.text("EXPENSE RECEIPT", pageWidth / 2, 25, { align: "center" })
      
      doc.setFontSize(12)
      doc.text(`Receipt #${expense.expenseNumber}`, pageWidth / 2, 40, { align: "center" })
      doc.text(`Generated on ${new Date().toLocaleDateString()}`, pageWidth / 2, 50, { align: "center" })

      let yPos = 80
      doc.setTextColor(0, 0, 0)
      
      autoTable(doc, {
        startY: yPos,
        head: [['Field', 'Details']],
        body: [
          ['Expense Number', `#${expense.expenseNumber}`],
          ['Title', expense.title],
          ['Amount', formatCurrencyForPDF(expense.amount, expense.currency)],
          ['Date', new Date(expense.date).toLocaleDateString('en-US', { 
            year: 'numeric', 
            month: 'long', 
            day: 'numeric' 
          })],
          ['User', expense.userName],
          ['User ID', expense.userSequentialId],
          ['Currency', expense.currency],
          ['Created', new Date(expense.createdAt).toLocaleString()],
          ['Notes', expense.notes || 'No additional notes']
        ],
        theme: 'grid',
        headStyles: {
          fillColor: [6, 182, 212],
          textColor: 255,
          fontStyle: 'bold'
        },
        styles: {
          fontSize: 10,
          cellPadding: 5,
        },
        columnStyles: {
          0: { fontStyle: 'bold', cellWidth: 40 },
          1: { cellWidth: 140 }
        }
      })

      const finalY = (doc as any).lastAutoTable.finalY + 20
      doc.setFontSize(8)
      doc.setTextColor(150, 150, 150)
      doc.text('This is an official receipt generated by ExpenseTracker', pageWidth / 2, finalY, { align: "center" })
      doc.text('Thank you for using our service!', pageWidth / 2, finalY + 5, { align: "center" })

      doc.save(`receipt-${expense.expenseNumber}-${expense._id}.pdf`)
    } catch (error) {
      console.error("PDF export failed:", error)
    }
  }, [expense, userProfile])

  const handlePrint = () => {
    window.print()
  }

  if (isLoading) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-slate-50 to-blue-50 dark:from-slate-950 dark:via-slate-900 dark:to-slate-800 flex items-center justify-center">
        <motion.div
          animate={{ rotate: 360 }}
          transition={{ duration: 1, repeat: Infinity, ease: "linear" }}
          className="w-16 h-16 border-4 border-cyan-500 border-t-transparent rounded-full"
        />
      </div>
    )
  }

  if (!expense || !userProfile) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-slate-50 to-blue-50 dark:from-slate-950 dark:via-slate-900 dark:to-slate-800 flex items-center justify-center">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="text-center space-y-6"
        >
          <div className="w-20 h-20 bg-red-500/20 rounded-2xl flex items-center justify-center mx-auto">
            <Receipt className="w-10 h-10 text-red-500" />
          </div>
          <p className="text-slate-700 dark:text-slate-300 text-xl">Expense not found</p>
          <motion.button
            onClick={() => router.back()}
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
            className="px-8 py-4 bg-cyan-600 hover:bg-cyan-700 text-white rounded-xl font-semibold transition-all duration-300"
          >
            Go Back
          </motion.button>
        </motion.div>
      </div>
    )
  }

  const date = new Date(expense.date).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  })

  return (
    <main className="min-h-screen bg-gradient-to-br from-slate-50 to-blue-50 dark:from-slate-950 dark:via-slate-900 dark:to-slate-800 py-8 px-4 print:bg-white">
      <div className="max-w-4xl mx-auto space-y-8">
        {/* Header Actions */}
        <motion.div 
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          className="flex flex-col sm:flex-row gap-4 justify-between items-start sm:items-center no-print"
        >
          <motion.button
            onClick={() => router.back()}
            whileHover={{ scale: 1.05, x: -5 }}
            whileTap={{ scale: 0.95 }}
            className="flex items-center gap-3 px-6 py-3 bg-white dark:bg-slate-800 hover:bg-slate-100 dark:hover:bg-slate-700 text-slate-900 dark:text-white rounded-xl font-semibold transition-all duration-300 border border-slate-300 dark:border-slate-600"
          >
            <ArrowLeft className="w-5 h-5" />
            Back to Dashboard
          </motion.button>
          
          <div className="flex gap-3">
            <motion.button
              onClick={handlePrint}
              whileHover={{ scale: 1.05, y: -2 }}
              whileTap={{ scale: 0.95 }}
              className="flex items-center gap-3 px-6 py-3 bg-cyan-600 hover:bg-cyan-700 text-white rounded-xl font-semibold transition-all duration-300 shadow-lg shadow-cyan-500/25"
            >
              <Printer className="w-5 h-5" />
              Print Receipt
            </motion.button>
            <motion.button
              onClick={handleExportPDF}
              whileHover={{ scale: 1.05, y: -2 }}
              whileTap={{ scale: 0.95 }}
              className="flex items-center gap-3 px-6 py-3 bg-blue-600 hover:bg-blue-700 text-white rounded-xl font-semibold transition-all duration-300 shadow-lg shadow-blue-500/25"
            >
              <Download className="w-5 h-5" />
              Export PDF
            </motion.button>
          </div>
        </motion.div>

        {/* Receipt Card */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.1 }}
          className="glass p-8 space-y-8 rounded-3xl border border-slate-300 dark:border-slate-600 shadow-2xl shadow-slate-500/10 dark:shadow-slate-900/10 print:shadow-none print:border print:border-gray-200 print:bg-white"
        >
          {/* Receipt Header */}
          <div className="text-center space-y-6 border-b border-slate-300 dark:border-slate-600 pb-8 print:border-gray-200">
            <motion.div
              initial={{ scale: 0 }}
              animate={{ scale: 1 }}
              transition={{ delay: 0.3, type: "spring" }}
              className="w-20 h-20 bg-gradient-to-r from-cyan-600 to-blue-700 rounded-2xl flex items-center justify-center mx-auto shadow-lg shadow-cyan-500/25"
            >
              <Receipt className="w-10 h-10 text-white" />
            </motion.div>
            <div>
              <h1 className="text-4xl font-bold bg-gradient-to-r from-cyan-600 to-blue-700 dark:from-cyan-400 dark:to-blue-500 bg-clip-text text-transparent print:text-black">
                Expense Receipt
              </h1>
              <p className="text-slate-600 dark:text-slate-400 print:text-gray-600 mt-2">Official Receipt #{expense.expenseNumber}</p>
            </div>
          </div>

          {/* Expense Details */}
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
            {/* Left Column */}
            <div className="space-y-6">
              <motion.div
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: 0.2 }}
                className="space-y-4"
              >
                <div className="flex items-center gap-3">
                  <div className="w-12 h-12 bg-cyan-500/20 rounded-xl flex items-center justify-center">
                    <FileText className="w-6 h-6 text-cyan-600 dark:text-cyan-400" />
                  </div>
                  <div>
                    <p className="text-slate-600 dark:text-slate-400 text-sm print:text-gray-600">Title</p>
                    <p className="text-xl font-semibold text-slate-900 dark:text-white print:text-black">{expense.title}</p>
                  </div>
                </div>

                <div className="flex items-center gap-3">
                  <div className="w-12 h-12 bg-blue-500/20 rounded-xl flex items-center justify-center">
                    <Hash className="w-6 h-6 text-blue-600 dark:text-blue-400" />
                  </div>
                  <div>
                    <p className="text-slate-600 dark:text-slate-400 text-sm print:text-gray-600">Expense Number</p>
                    <p className="text-xl font-semibold text-slate-900 dark:text-white print:text-black">#{expense.expenseNumber}</p>
                  </div>
                </div>

                <div className="flex items-center gap-3">
                  <div className="w-12 h-12 bg-purple-500/20 rounded-xl flex items-center justify-center">
                    <Calendar className="w-6 h-6 text-purple-600 dark:text-purple-400" />
                  </div>
                  <div>
                    <p className="text-slate-600 dark:text-slate-400 text-sm print:text-gray-600">Date</p>
                    <p className="text-xl font-semibold text-slate-900 dark:text-white print:text-black">{date}</p>
                  </div>
                </div>
              </motion.div>
            </div>

            {/* Right Column */}
            <div className="space-y-6">
              <motion.div
                initial={{ opacity: 0, x: 20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: 0.3 }}
                className="space-y-6"
              >
                {/* Amount Display */}
                <div className="text-center p-6 bg-gradient-to-r from-cyan-500/20 to-blue-600/20 rounded-2xl border border-cyan-500/30 print:bg-gray-100">
                  <p className="text-slate-600 dark:text-slate-400 print:text-gray-600 mb-2">Total Amount</p>
                  <p className="text-5xl font-bold bg-gradient-to-r from-cyan-600 to-blue-700 dark:from-cyan-400 dark:to-blue-500 bg-clip-text text-transparent print:text-black">
                    {formatCurrency(expense.amount, expense.currency)}
                  </p>
                  <p className="text-slate-600 dark:text-slate-400 print:text-gray-600 mt-2">
                    Currency: {expense.currency} ({getCurrencySymbol(expense.currency)})
                  </p>
                </div>

                {/* User Information with Profile Image */}
                <div className="space-y-4">
                  <div className="flex items-center gap-3">
                    <div>
                      <p className="text-slate-600 dark:text-slate-400 print:text-gray-600">User Information</p>
                      <div className="flex items-center gap-3 mt-2">
                        {userProfile.profileImage ? (
                          <img
                            src={userProfile.profileImage}
                            alt={userProfile.name}
                            className="w-12 h-12 rounded-lg object-cover"
                          />
                        ) : (
                          <div className="w-8 h-8 rounded-lg bg-gradient-to-r from-cyan-600 to-blue-700 flex items-center justify-center text-white text-xs font-bold">
                            {userProfile.name?.charAt(0)}
                          </div>
                        )}
                        <div>
                          <p className="text-slate-900 dark:text-white print:text-black font-semibold">{expense.userName}</p>
                          <p className="text-slate-600 dark:text-slate-400 print:text-gray-600 text-sm">ID: {expense.userSequentialId}</p>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </motion.div>
            </div>
          </div>

          {/* Notes Section */}
          {expense.notes && (
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.4 }}
              className="pt-6 border-t border-slate-300 dark:border-slate-600 print:border-gray-200"
            >
              <p className="text-slate-600 dark:text-slate-400 print:text-gray-600 mb-3">Additional Notes</p>
              <div className="p-4 bg-white dark:bg-slate-800 print:bg-gray-100 rounded-xl border border-slate-300 dark:border-slate-600 print:border-gray-200">
                <p className="text-slate-900 dark:text-white print:text-black leading-relaxed">{expense.notes}</p>
              </div>
            </motion.div>
          )}

          {/* Footer */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 0.5 }}
            className="pt-6 border-t border-slate-300 dark:border-slate-600 print:border-gray-200 text-center space-y-2"
          >
            <p className="text-slate-500 dark:text-slate-500 print:text-gray-600 text-sm">
              Receipt ID: {expense._id} • Created: {new Date(expense.createdAt).toLocaleString()}
            </p>
            <p className="text-slate-500 dark:text-slate-500 print:text-gray-600 text-sm">
              This is an official receipt generated by ExpenseTracker
            </p>
          </motion.div>
        </motion.div>
      </div>

      {/* Print Styles */}
      <style jsx global>{`
        @media print {
          .no-print {
            display: none !important;
          }
          body {
            background: white !important;
          }
        }
      `}</style>
    </main>
  )
}